# Generated by Django 5.2.4 on 2025-08-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='app.habitacion'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
