# Generated by Django 5.2.4 on 2025-08-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_residente_estado_alter_residente_habitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='zonas',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='desactivada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='zona',
            field=models.CharField(choices=[('Castillo', 'Castillo'), ('Restaurante', 'Restaurante'), ('Piso', 'Piso'), ('Vilanova', 'Vilanova')], default='Castillo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='nomenclatura',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tamaño',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='litera',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='litera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
