# Generated by Django 5.2.4 on 2025-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_habitacion_zonas_habitacion_desactivada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
